language: node_js
os: linux
dist: xenial
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
before_deploy: |-
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  export TAG=$TRAVIS_COMMIT_MESSAGE
  export BODY=$'**Changelog:**<br/>'${log//$'\n'/<br/>}
  export RELEASE_NAME=$'cutter-'$TAG
  export RELEASE_ZIP_NAME=$RELEASE_NAME$'.zip'
  cp -R dist $RELEASE_NAME
  zip -r $RELEASE_ZIP_NAME $RELEASE_NAME
deploy:
  provider: releases
  token: $GITHUB_OAUTH_TOKEN
  name: $TAG
  tag_name: $TAG
  release_notes: $BODY
  file: $RELEASE_ZIP_NAME
  cleanup: false
  on:
    branch: master
script:
  - npm run build
