language: node_js
os: linux
dist: xenial
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
before_install: |-
  source ./bin/variables.sh
before_deploy: |-
  chmod +x ./bin/prepare-release.sh
  ./bin/prepare-release.sh
deploy:
  provider: releases
  token: $GITHUB_OAUTH_TOKEN
  name: $RELEASE_NAME
  tag_name: $RELEASE_TAG_NAME
  file: $RELEASE_FILE
  cleanup: false
  on:
    branch: master
script:
  - npm run build
