language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist"
  skip_cleanup: true
  on:
    tags: true
script:
  - npm build
